- name: Install raspberry pi imager
  community.general.pacman:
    name:
      - rpi-imager
    state: present
  become: true

- name: Setup virtualization and containerization
  ansible.builtin.include_tasks:
    file: virt.yml