- name: Install dotfiles manager
  community.general.pacman:
    name:
      - chezmoi
    state: present
  become: true

- name: Setup dotfiles
  ansible.builtin.shell: chezmoi init --apply {{ dotfiles_repo }}
  register: command_result
  failed_when: command_result.rc != 0