- name: Install and setup core utilities
  ansible.builtin.include_tasks:
    file: core.yml

- name: Install and setup compression utilities
  ansible.builtin.include_tasks:
    file: compression.yml

- name: Install and setup ssh
  ansible.builtin.include_tasks:
    file: ssh.yml

- name: Install file manager
  community.general.pacman:
    name:
      - yazi
    state: present
  become: true

- name: Install web browser
  ansible.builtin.include_tasks: tasks/yay_package.yml
  vars:
    yay_packages:
      - librewolf-bin
  become: true