- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true
  become: true

- name: Regenerate grub config
  ansible.builtin.command:
    cmd: grub-mkconfig -o /boot/grub/grub.cfg
  become: true
  changed_when: true