- name: Install terminal emulator
  community.general.pacman:
    name:
      - ghostty
    state: present
  become: true

- name: Install shell
  community.general.pacman:
    name:
      - fish
    state: present
  become: true

- name: Set user shell
  ansible.builtin.user:
    name: "{{ username }}"
    shell: /usr/bin/fish

- name: Install terminal multiplexer
  community.general.pacman:
    name:
      - tmux
    state: present
  become: true