- name: Remove nullok from Arch system-auth
  ansible.builtin.replace:
    path: /etc/pam.d/system-auth
    regexp: '(^\s*(?:auth|account|password|session)\s+(?:\[[^\]]+\]|\S+)\s+pam_unix\.so(?:\s+\S+)*?)\s+nullok(?=\s|$)'
    replace: '\1'
    backup: true

- name: Install libpwquality
  community.general.pacman:
    name: libpwquality
    state: present

- name: Configure password quality and pam_unix in Arch system-auth
  ansible.builtin.replace:
    path: /etc/pam.d/system-auth
    backup: true
    regexp: '(?m)^password\s+required\s+pam_unix\.so.*$'
    replace: |
      password required pam_pwquality.so retry=2 minlen=10 difok=6 dcredit=-1 ucredit=-1 ocredit=-1 lcredit=-1 badwords=myservice,mydomain enforce_for_root
      password required pam_unix.so use_authtok yescrypt shadow