- name: Run pacman upgrade
  pacman: 
    update_cache: yes
    upgrade: yes

- name: Configure pacman
  ansible.builtin.include_tasks:
    file: pacman.yaml

- name: Check if yay is installed
  ansible.builtin.stat:
    path: /usr/bin/yay
  register: yay_status

- name: Install and configure yay
  ansible.builtin.include_tasks:
    file: yay.yaml
  when: not yay_status.stat.exists

- name: Run yay upgrade
  ansible.builtin.shell: yay
  register: command_result
  failed_when: command_result.rc != 0