- name: Create AUR directory
  file: path={{ aur_path }}
        state=directory
        owner={{ username }}
        group={{ username }}

- name: Install yay dependencies
  community.general.pacman:
    name: '{{ item }}'
    state: present
  loop: '{{ yay_deps }}'
  become: true

- name: Clone and checkout yay repo
  ansible.builtin.git:
    repo: '{{ yay_repo }}'
    dest: '{{ yay_repo_dir }}'

- name: Build and install yay
  ansible.builtin.shell: makepkg -si --noconfirm
  args:
    chdir: '{{ yay_repo_dir }}'
  register: command_result
  failed_when: command_result.rc != 0