- name: Install Pipewire
  community.general.pacman:
    name:
      - pipewire
      - wireplumber
      - pipewire-pulse
    state: present
  become: true

- name: Install audio config apps
  community.general.pacman:
    name: 
      - pavucontrol
      - qpwgraph
    state: present
  become: true