- name: Install copy/paste utilty
  community.general.pacman:
   name: 
    - wl-clipboard
   state: present

- name: Install clipboard manager
  ansible.builtin.include_tasks: tasks/yay_package.yml
  vars:
    yay_packages:
      - clipvault