- name: Install Hyprland
  community.general.pacman:
    name: 
      - hyprland
    state: present
  become: true

- name: Ensure hyprland config directory exists
  file: path={{ hyprland_config_dir }}
        state=directory
        owner={{ username }}
        group={{ username }}

- name: Generate hyprland config from template
  ansible.builtin.template:
    src: hyprland.lua.j2
    dest: "{{ hyprland_config_path }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0644'