- name: Install Nvidia drivers and utilities
  community.general.pacman:
    name: 
      - nvidia-open-dkms
      - nvidia-utils
      - lib32-nvidia-utils
      - egl-wayland
    state: present
  become: true
  
- name: Install status bar
  community.general.pacman:
    name: 
      - waybar
    state: present
  become: true

- name: Enable and start waybar config watcher
  ansible.builtin.systemd_service:
    name: waybar-config-watcher.service
    scope: user
    daemon_reload: true
    enabled: true
    state: started

- name: Install wallpaper utility
  community.general.pacman:
    name: 
      - hyprpaper
    state: present
  become: true

- name: Ensure wallpaper directory exists
  ansible.builtin.file:
    path: "{{ wallpaper_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  become: true

- name: Download wallpaper
  ansible.builtin.shell: "ffmpeg -ss 00:00:00 -i (ytdl -f bv -g '{{ wallpaper_url }}') -vframes 1 {{ wallpaper_path }}"
  chdir: /tmp
  register: command_result
  failed_when: command_result.rc != 0

- name: Install app launcher & extensions
  community.general.pacman:
    name: 
      - rofi
      - rofi-calc
    state: present
  become: true

- name: Install color picker
  community.general.pacman:
    name: 
      - hyprpicker
    state: present
  become: true

- name: Install notification daemon
  community.general.pacman:
    name: 
      - dunst
    state: present
  become: true

- name: Install authentication daemon
  community.general.pacman:
    name: 
      - hyprpolkitagent
    state: present
  become: true

- name: Install device mounting utility
  community.general.pacman:
    name: 
      - udisks2
      - udiskie
    state: present
  become: true

- name: Install brightness controlling utilities
  community.general.pacman:
    name: 
      - brightnessctl
      - ddcutil
    state: present
  become: true

- name: Install quickshell
  community.general.pacman:
    name:
      - quickshell
    state: present
  become: true

- name: Install display management software
  community.general.pacman:
    name:
      - nwg-displays
    state: present
  become: true

- name: Install and setup XDG
  ansible.builtin.include_tasks:
    file: xdg.yml

- name: Install and setup fonts
  ansible.builtin.include_tasks:
    file: fonts.yml

- name: Install and setup themes
  ansible.builtin.include_tasks:
    file: themes.yml

- name: Setup clipboard
  ansible.builtin.include_tasks:
    file: clipboard.yml

- name: Install and setup capture utilities
  ansible.builtin.include_tasks:
    file: capture.yml

- name: Install and setup Hyprland
  ansible.builtin.include_tasks:
    file: hyprland.yml

- name: Install and setup display manager
  ansible.builtin.include_tasks:
    file: login.yml