- name: Install GTK
  community.general.pacman:
    name: 
      - gtk3
      - gtk4
    state: present
  become: true

- name: Install QT Wayland support
  community.general.pacman:
    name: 
      - qt5-wayland
      - qt6-wayland
      - qt6-5compat
    state: present
  become: true

- name: Install theme picker
  community.general.pacman:
    name: 
      - nwg-look
    state: present
  become: true

- name: Install nordic theme
  ansible.builtin.include_tasks: tasks/yay_package.yml
  vars:
    yay_packages:
      - makemkv